# Generated by Django 5.1.7 on 2025-03-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_group_permissions_user_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='entrepise',
            new_name='enterpise',
        ),
    ]
