# Generated by Django 5.1.7 on 2025-03-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_entrepise_group_enterpise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='enterpise',
            new_name='enterprise',
        ),
    ]
