# Generated by Django 5.1.7 on 2025-03-14 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_group_permissions_user_groups'),
        ('companies', '0003_taskstatus_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entreprise',
            new_name='Enterprise',
        ),
    ]
