# Generated by Django 5.1.7 on 2025-03-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_entreprise_enterprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
